# Helper to make constant replacements way faster and easier to code
class ConstantReplacer:
    def __init__(self, constants: dict):
        self.constants = constants

    def __call__(self, value):
        return self.constants.get(value, value)


SURFACES = ConstantReplacer(
    {
        0x0000: "SURFACE_DEFAULT",
        0x0001: "SURFACE_BURNING",
        0x0004: "SURFACE_0004",
        0x0005: "SURFACE_HANGABLE",
        0x0009: "SURFACE_SLOW",
        0x000A: "SURFACE_DEATH_PLANE",
        0x000B: "SURFACE_CLOSE_CAMERA",
        0x000D: "SURFACE_WATER",
        0x000E: "SURFACE_FLOWING_WATER",
        0x0012: "SURFACE_INTANGIBLE",
        0x0013: "SURFACE_VERY_SLIPPERY",
        0x0014: "SURFACE_SLIPPERY",
        0x0015: "SURFACE_NOT_SLIPPERY",
        0x0016: "SURFACE_TTM_VINES",
        0x001A: "SURFACE_MGR_MUSIC",
        0x001B: "SURFACE_INSTANT_WARP_1B",
        0x001C: "SURFACE_INSTANT_WARP_1C",
        0x001D: "SURFACE_INSTANT_WARP_1D",
        0x001E: "SURFACE_INSTANT_WARP_1E",
        0x0021: "SURFACE_SHALLOW_QUICKSAND",
        0x0022: "SURFACE_DEEP_QUICKSAND",
        0x0023: "SURFACE_INSTANT_QUICKSAND",
        0x0024: "SURFACE_DEEP_MOVING_QUICKSAND",
        0x0025: "SURFACE_SHALLOW_MOVING_QUICKSAND",
        0x0026: "SURFACE_QUICKSAND",
        0x0027: "SURFACE_MOVING_QUICKSAND",
        0x0028: "SURFACE_WALL_MISC",
        0x0029: "SURFACE_NOISE_DEFAULT",
        0x002A: "SURFACE_NOISE_SLIPPERY",
        0x002C: "SURFACE_HORIZONTAL_WIND",
        0x002D: "SURFACE_INSTANT_MOVING_QUICKSAND",
        0x002E: "SURFACE_ICE",
        0x002F: "SURFACE_LOOK_UP_WARP",
        0x0030: "SURFACE_HARD",
        0x0032: "SURFACE_WARP",
        0x0033: "SURFACE_TIMER_START",
        0x0034: "SURFACE_TIMER_END",
        0x0035: "SURFACE_HARD_SLIPPERY",
        0x0036: "SURFACE_HARD_VERY_SLIPPERY",
        0x0037: "SURFACE_HARD_NOT_SLIPPERY",
        0x0038: "SURFACE_VERTICAL_WIND",
        0x0065: "SURFACE_BOSS_FIGHT_CAMERA",
        0x0066: "SURFACE_CAMERA_FREE_ROAM",
        0x0068: "SURFACE_THI3_WALLKICK",
        0x0069: "SURFACE_CAMERA_8_DIR",
        0x006E: "SURFACE_CAMERA_MIDDLE",
        0x006F: "SURFACE_CAMERA_ROTATE_RIGHT",
        0x0070: "SURFACE_CAMERA_ROTATE_LEFT",
        0x0072: "SURFACE_CAMERA_BOUNDARY",
        0x0073: "SURFACE_NOISE_VERY_SLIPPERY_73",
        0x0074: "SURFACE_NOISE_VERY_SLIPPERY_74",
        0x0075: "SURFACE_NOISE_VERY_SLIPPERY",
        0x0076: "SURFACE_NO_CAM_COLLISION",
        0x0077: "SURFACE_NO_CAM_COLLISION_77",
        0x0078: "SURFACE_NO_CAM_COL_VERY_SLIPPERY",
        0x0079: "SURFACE_NO_CAM_COL_SLIPPERY",
        0x007A: "SURFACE_SWITCH",
        0x007B: "SURFACE_VANISH_CAP_WALLS",
        0x00A6: "SURFACE_PAINTING_WOBBLE_A6",
        0x00A7: "SURFACE_PAINTING_WOBBLE_A7",
        0x00A8: "SURFACE_PAINTING_WOBBLE_A8",
        0x00A9: "SURFACE_PAINTING_WOBBLE_A9",
        0x00AA: "SURFACE_PAINTING_WOBBLE_AA",
        0x00AB: "SURFACE_PAINTING_WOBBLE_AB",
        0x00AC: "SURFACE_PAINTING_WOBBLE_AC",
        0x00AD: "SURFACE_PAINTING_WOBBLE_AD",
        0x00AE: "SURFACE_PAINTING_WOBBLE_AE",
        0x00AF: "SURFACE_PAINTING_WOBBLE_AF",
        0x00B0: "SURFACE_PAINTING_WOBBLE_B0",
        0x00B1: "SURFACE_PAINTING_WOBBLE_B1",
        0x00B2: "SURFACE_PAINTING_WOBBLE_B2",
        0x00B3: "SURFACE_PAINTING_WOBBLE_B3",
        0x00B4: "SURFACE_PAINTING_WOBBLE_B4",
        0x00B5: "SURFACE_PAINTING_WOBBLE_B5",
        0x00B6: "SURFACE_PAINTING_WOBBLE_B6",
        0x00B7: "SURFACE_PAINTING_WOBBLE_B7",
        0x00B8: "SURFACE_PAINTING_WOBBLE_B8",
        0x00B9: "SURFACE_PAINTING_WOBBLE_B9",
        0x00BA: "SURFACE_PAINTING_WOBBLE_BA",
        0x00BB: "SURFACE_PAINTING_WOBBLE_BB",
        0x00BC: "SURFACE_PAINTING_WOBBLE_BC",
        0x00BD: "SURFACE_PAINTING_WOBBLE_BD",
        0x00BE: "SURFACE_PAINTING_WOBBLE_BE",
        0x00BF: "SURFACE_PAINTING_WOBBLE_BF",
        0x00C0: "SURFACE_PAINTING_WOBBLE_C0",
        0x00C1: "SURFACE_PAINTING_WOBBLE_C1",
        0x00C2: "SURFACE_PAINTING_WOBBLE_C2",
        0x00C3: "SURFACE_PAINTING_WOBBLE_C3",
        0x00C4: "SURFACE_PAINTING_WOBBLE_C4",
        0x00C5: "SURFACE_PAINTING_WOBBLE_C5",
        0x00C6: "SURFACE_PAINTING_WOBBLE_C6",
        0x00C7: "SURFACE_PAINTING_WOBBLE_C7",
        0x00C8: "SURFACE_PAINTING_WOBBLE_C8",
        0x00C9: "SURFACE_PAINTING_WOBBLE_C9",
        0x00CA: "SURFACE_PAINTING_WOBBLE_CA",
        0x00CB: "SURFACE_PAINTING_WOBBLE_CB",
        0x00CC: "SURFACE_PAINTING_WOBBLE_CC",
        0x00CD: "SURFACE_PAINTING_WOBBLE_CD",
        0x00CE: "SURFACE_PAINTING_WOBBLE_CE",
        0x00CF: "SURFACE_PAINTING_WOBBLE_CF",
        0x00D0: "SURFACE_PAINTING_WOBBLE_D0",
        0x00D1: "SURFACE_PAINTING_WOBBLE_D1",
        0x00D2: "SURFACE_PAINTING_WOBBLE_D2",
        0x00D3: "SURFACE_PAINTING_WARP_D3",
        0x00D4: "SURFACE_PAINTING_WARP_D4",
        0x00D5: "SURFACE_PAINTING_WARP_D5",
        0x00D6: "SURFACE_PAINTING_WARP_D6",
        0x00D7: "SURFACE_PAINTING_WARP_D7",
        0x00D8: "SURFACE_PAINTING_WARP_D8",
        0x00D9: "SURFACE_PAINTING_WARP_D9",
        0x00DA: "SURFACE_PAINTING_WARP_DA",
        0x00DB: "SURFACE_PAINTING_WARP_DB",
        0x00DC: "SURFACE_PAINTING_WARP_DC",
        0x00DD: "SURFACE_PAINTING_WARP_DD",
        0x00DE: "SURFACE_PAINTING_WARP_DE",
        0x00DF: "SURFACE_PAINTING_WARP_DF",
        0x00E0: "SURFACE_PAINTING_WARP_E0",
        0x00E1: "SURFACE_PAINTING_WARP_E1",
        0x00E2: "SURFACE_PAINTING_WARP_E2",
        0x00E3: "SURFACE_PAINTING_WARP_E3",
        0x00E4: "SURFACE_PAINTING_WARP_E4",
        0x00E5: "SURFACE_PAINTING_WARP_E5",
        0x00E6: "SURFACE_PAINTING_WARP_E6",
        0x00E7: "SURFACE_PAINTING_WARP_E7",
        0x00E8: "SURFACE_PAINTING_WARP_E8",
        0x00E9: "SURFACE_PAINTING_WARP_E9",
        0x00EA: "SURFACE_PAINTING_WARP_EA",
        0x00EB: "SURFACE_PAINTING_WARP_EB",
        0x00EC: "SURFACE_PAINTING_WARP_EC",
        0x00ED: "SURFACE_PAINTING_WARP_ED",
        0x00EE: "SURFACE_PAINTING_WARP_EE",
        0x00EF: "SURFACE_PAINTING_WARP_EF",
        0x00F0: "SURFACE_PAINTING_WARP_F0",
        0x00F1: "SURFACE_PAINTING_WARP_F1",
        0x00F2: "SURFACE_PAINTING_WARP_F2",
        0x00F3: "SURFACE_PAINTING_WARP_F3",
        0x00F4: "SURFACE_TTC_PAINTING_1",
        0x00F5: "SURFACE_TTC_PAINTING_2",
        0x00F6: "SURFACE_TTC_PAINTING_3",
        0x00F7: "SURFACE_PAINTING_WARP_F7",
        0x00F8: "SURFACE_PAINTING_WARP_F8",
        0x00F9: "SURFACE_PAINTING_WARP_F9",
        0x00FA: "SURFACE_PAINTING_WARP_FA",
        0x00FB: "SURFACE_PAINTING_WARP_FB",
        0x00FC: "SURFACE_PAINTING_WARP_FC",
        0x00FD: "SURFACE_WOBBLING_WARP",
        0x00FF: "SURFACE_TRAPDOOR",
    }
)

macro_presets = {
    i: name
    for i, name in enumerate(
        [
            "macro_yellow_coin",
            "macro_yellow_coin_2",
            "macro_moving_blue_coin",
            "macro_sliding_blue_coin",
            "macro_red_coin",
            "macro_empty_5",
            "macro_coin_line_horizontal",
            "macro_coin_ring_horizontal",
            "macro_coin_arrow",
            "macro_coin_line_horizontal_flying",
            "macro_coin_line_vertical",
            "macro_coin_ring_horizontal_flying",
            "macro_coin_ring_vertical",
            "macro_coin_arrow_flying",
            "macro_hidden_star_trigger",
            "macro_empty_15",
            "macro_empty_16",
            "macro_empty_17",
            "macro_empty_18",
            "macro_empty_19",
            "macro_fake_star",
            "macro_wooden_signpost",
            "macro_cannon_closed",
            "macro_bobomb_buddy_opens_cannon",
            "macro_butterfly",
            "macro_bouncing_fireball_copy",
            "macro_fish_group_3",
            "macro_fish_group",
            "macro_unknown_28",
            "macro_hidden_1up_in_pole",
            "macro_huge_goomba",
            "macro_tiny_goomba",
            "macro_goomba_triplet_spawner",
            "macro_goomba_quintuplet_spawner",
            "macro_sign_on_wall",
            "macro_chuckya",
            "macro_cannon_open",
            "macro_goomba",
            "macro_homing_amp",
            "macro_circling_amp",
            "macro_unknown_40",
            "macro_unknown_41",
            "macro_free_bowling_ball",
            "macro_snufit",
            "macro_recovery_heart",
            "macro_1up_sliding",
            "macro_1up",
            "macro_1up_jump_on_approach",
            "macro_hidden_1up",
            "macro_hidden_1up_trigger",
            "macro_1up_2",
            "macro_1up_3",
            "macro_empty_52",
            "macro_blue_coin_switch",
            "macro_hidden_blue_coin",
            "macro_wing_cap_switch",
            "macro_metal_cap_switch",
            "macro_vanish_cap_switch",
            "macro_yellow_cap_switch",
            "macro_unknown_59",
            "macro_box_wing_cap",
            "macro_box_metal_cap",
            "macro_box_vanish_cap",
            "macro_box_koopa_shell",
            "macro_box_one_coin",
            "macro_box_three_coins",
            "macro_box_ten_coins",
            "macro_box_1up",
            "macro_box_star_1",
            "macro_breakable_box_no_coins",
            "macro_breakable_box_three_coins",
            "macro_pushable_metal_box",
            "macro_breakable_box_small",
            "macro_floor_switch_hidden_objects",
            "macro_hidden_box",
            "macro_hidden_object_2",
            "macro_hidden_object_3",
            "macro_breakable_box_giant",
            "macro_koopa_shell_underwater",
            "macro_box_1up_running_away",
            "macro_empty_80",
            "macro_bullet_bill_cannon",
            "macro_heave_ho",
            "macro_empty_83",
            "macro_thwomp",
            "macro_fire_spitter",
            "macro_fire_fly_guy",
            "macro_jumping_box",
            "macro_butterfly_triplet",
            "macro_butterfly_triplet_2",
            "macro_empty_90",
            "macro_empty_91",
            "macro_empty_92",
            "macro_bully",
            "macro_bully_2",
            "macro_empty_95",
            "macro_unknown_96",
            "macro_bouncing_fireball",
            "macro_flamethrower",
            "macro_empty_99",
            "macro_empty_100",
            "macro_empty_101",
            "macro_empty_102",
            "macro_empty_103",
            "macro_empty_104",
            "macro_empty_105",
            "macro_wooden_post",
            "macro_water_bomb_spawner",
            "macro_enemy_lakitu",
            "macro_bob_koopa_the_quick",
            "macro_koopa_race_endpoint",
            "macro_bobomb",
            "macro_water_bomb_cannon_copy",
            "macro_bobomb_buddy_opens_cannon_copy",
            "macro_water_bomb_cannon",
            "macro_bobomb_still",
            "macro_empty_116",
            "macro_empty_117",
            "macro_empty_118",
            "macro_empty_119",
            "macro_empty_120",
            "macro_empty_121",
            "macro_empty_122",
            "macro_unknown_123",
            "macro_empty_124",
            "macro_unagi",
            "macro_sushi",
            "macro_empty_127",
            "macro_empty_128",
            "macro_empty_129",
            "macro_empty_130",
            "macro_empty_131",
            "macro_empty_132",
            "macro_empty_133",
            "macro_empty_134",
            "macro_empty_135",
            "macro_empty_136",
            "macro_unknown_137",
            "macro_tornado",
            "macro_pokey",
            "macro_pokey_copy",
            "macro_tox_box",
            "macro_empty_142",
            "macro_empty_143",
            "macro_empty_144",
            "macro_empty_145",
            "macro_empty_146",
            "macro_empty_147",
            "macro_empty_148",
            "macro_empty_149",
            "macro_empty_150",
            "macro_monty_mole_2",
            "macro_monty_mole",
            "macro_monty_mole_hole",
            "macro_fly_guy",
            "macro_empty_155",
            "macro_wiggler",
            "macro_empty_157",
            "macro_empty_158",
            "macro_empty_159",
            "macro_empty_160",
            "macro_empty_161",
            "macro_empty_162",
            "macro_empty_163",
            "macro_empty_164",
            "macro_spindrift",
            "macro_mr_blizzard",
            "macro_mr_blizzard_copy",
            "macro_empty_168",
            "macro_small_penguin",
            "macro_tuxies_mother",
            "macro_tuxies_mother_copy",
            "macro_mr_blizzard_2",
            "macro_empty_173",
            "macro_empty_174",
            "macro_empty_175",
            "macro_empty_176",
            "macro_empty_177",
            "macro_empty_178",
            "macro_empty_179",
            "macro_empty_180",
            "macro_empty_181",
            "macro_empty_182",
            "macro_empty_183",
            "macro_empty_184",
            "macro_empty_185",
            "macro_empty_186",
            "macro_empty_187",
            "macro_empty_188",
            "macro_haunted_chair_copy",
            "macro_haunted_chair",
            "macro_haunted_chair_copy2",
            "macro_boo",
            "macro_boo_copy",
            "macro_boo_group",
            "macro_boo_with_cage",
            "macro_beta_key",
            "macro_empty_197",
            "macro_empty_198",
            "macro_empty_199",
            "macro_empty_200",
            "macro_empty_201",
            "macro_empty_202",
            "macro_empty_203",
            "macro_empty_204",
            "macro_empty_205",
            "macro_empty_206",
            "macro_empty_207",
            "macro_empty_208",
            "macro_empty_209",
            "macro_empty_210",
            "macro_empty_211",
            "macro_empty_212",
            "macro_empty_213",
            "macro_empty_214",
            "macro_empty_215",
            "macro_empty_216",
            "macro_empty_217",
            "macro_empty_218",
            "macro_empty_219",
            "macro_empty_220",
            "macro_empty_221",
            "macro_empty_222",
            "macro_empty_223",
            "macro_empty_224",
            "macro_empty_225",
            "macro_empty_226",
            "macro_empty_227",
            "macro_empty_228",
            "macro_empty_229",
            "macro_empty_230",
            "macro_empty_231",
            "macro_empty_232",
            "macro_empty_233",
            "macro_chirp_chirp",
            "macro_seaweed_bundle",
            "macro_beta_chest",
            "macro_water_mine",
            "macro_fish_group_4",
            "macro_fish_group_2",
            "macro_jet_stream_ring_spawner",
            "macro_jet_stream_ring_spawner_copy",
            "macro_skeeter",
            "macro_clam_shell",
            "macro_empty_244",
            "macro_empty_245",
            "macro_empty_246",
            "macro_empty_247",
            "macro_empty_248",
            "macro_empty_249",
            "macro_empty_250",
            "macro_ukiki",
            "macro_ukiki_2",
            "macro_piranha_plant",
            "macro_empty_254",
            "macro_whomp",
            "macro_chain_chomp",
            "macro_empty_257",
            "macro_koopa",
            "macro_koopa_shellless",
            "macro_wooden_post_copy",
            "macro_fire_piranha_plant",
            "macro_fire_piranha_plant_2",
            "macro_thi_koopa_the_quick",
            "macro_empty_264",
            "macro_empty_265",
            "macro_empty_266",
            "macro_empty_267",
            "macro_empty_268",
            "macro_empty_269",
            "macro_empty_270",
            "macro_empty_271",
            "macro_empty_272",
            "macro_empty_273",
            "macro_empty_274",
            "macro_empty_275",
            "macro_empty_276",
            "macro_empty_277",
            "macro_empty_278",
            "macro_empty_279",
            "macro_empty_280",
            "macro_moneybag",
            "macro_empty_282",
            "macro_empty_283",
            "macro_empty_284",
            "macro_empty_285",
            "macro_empty_286",
            "macro_empty_287",
            "macro_empty_288",
            "macro_swoop",
            "macro_swoop_2",
            "macro_mr_i",
            "macro_scuttlebug_spawner",
            "macro_scuttlebug",
            "macro_empty_294",
            "macro_empty_295",
            "macro_empty_296",
            "macro_empty_297",
            "macro_empty_298",
            "macro_empty_299",
            "macro_empty_300",
            "macro_empty_301",
            "macro_empty_302",
            "macro_unknown_303",
            "macro_empty_304",
            "macro_empty_305",
            "macro_empty_306",
            "macro_empty_307",
            "macro_empty_308",
            "macro_empty_309",
            "macro_empty_310",
            "macro_empty_311",
            "macro_empty_312",
            "macro_ttc_rotating_cube",
            "macro_ttc_rotating_prism",
            "macro_ttc_pendulum",
            "macro_ttc_large_treadmill",
            "macro_ttc_small_treadmill",
            "macro_ttc_push_block",
            "macro_ttc_rotating_hexagon",
            "macro_ttc_rotating_triangle",
            "macro_ttc_pit_block",
            "macro_ttc_pit_block_2",
            "macro_ttc_elevator_platform",
            "macro_ttc_clock_hand",
            "macro_ttc_spinner",
            "macro_ttc_small_gear",
            "macro_ttc_large_gear",
            "macro_ttc_large_treadmill_2",
            "macro_ttc_small_treadmill_2",
            "macro_empty_330",
            "macro_empty_331",
            "macro_empty_332",
            "macro_empty_333",
            "macro_empty_334",
            "macro_empty_335",
            "macro_empty_336",
            "macro_empty_337",
            "macro_empty_338",
            "macro_box_star_2",
            "macro_box_star_3",
            "macro_box_star_4",
            "macro_box_star_5",
            "macro_box_star_6",
            "macro_empty_344",
            "macro_empty_345",
            "macro_empty_346",
            "macro_empty_347",
            "macro_empty_348",
            "macro_empty_349",
            "macro_bits_sliding_platform",
            "macro_bits_twin_sliding_platforms",
            "macro_bits_unknown_352",
            "macro_bits_octagonal_platform",
            "macro_bits_staircase",
            "macro_empty_355",
            "macro_empty_356",
            "macro_bits_ferris_wheel_axle",
            "macro_bits_arrow_platform",
            "macro_bits_seesaw_platform",
            "macro_bits_tilting_w_platform",
            "macro_empty_361",
            "macro_empty_362",
            "macro_empty_363",
            "macro_empty_364",
            "macro_empty_365",
        ]
    )
}
