gDynosBuiltinScriptPtrs = [
    "level_main_scripts_entry",
    "script_func_global_1",
    "script_func_global_2",
    "script_func_global_3",
    "script_func_global_4",
    "script_func_global_5",
    "script_func_global_6",
    "script_func_global_7",
    "script_func_global_8",
    "script_func_global_9",
    "script_func_global_10",
    "script_func_global_11",
    "script_func_global_12",
    "script_func_global_13",
    "script_func_global_14",
    "script_func_global_15",
    "script_func_global_16",
    "script_func_global_17",
    "script_func_global_18",
    "level_bbh_entry",
    "level_bitdw_entry",
    "level_bitfs_entry",
    "level_bits_entry",
    "level_bob_entry",
    "level_bowser_1_entry",
    "level_bowser_2_entry",
    "level_bowser_3_entry",
    "level_castle_courtyard_entry",
    "level_castle_grounds_entry",
    "level_castle_inside_entry",
    "level_ccm_entry",
    "level_cotmc_entry",
    "level_ddd_entry",
    "level_ending_entry",
    "level_hmc_entry",
    "level_jrb_entry",
    "level_lll_entry",
    "level_pss_entry",
    "level_rr_entry",
    "level_sa_entry",
    "level_sl_entry",
    "level_ssl_entry",
    "level_thi_entry",
    "level_totwc_entry",
    "level_ttc_entry",
    "level_ttm_entry",
    "level_vcutm_entry",
    "level_wdw_entry",
    "level_wf_entry",
    "level_wmotr_entry",
    "level_main_menu_entry_1",
]

gDynosBuiltinLvlMacros = [
    "bbh_seg7_macro_objs",
    "bitdw_seg7_macro_objs",
    "bitfs_seg7_macro_objs",
    "bits_seg7_macro_objs",
    "bob_seg7_macro_objs",
    "castle_courtyard_seg7_macro_objs",
    "castle_grounds_seg7_macro_objs",
    "ccm_seg7_area_1_macro_objs",
    "ccm_seg7_area_2_macro_objs",
    "cotmc_seg7_macro_objs",
    "ddd_seg7_area_1_macro_objs",
    "ddd_seg7_area_2_macro_objs",
    "hmc_seg7_macro_objs",
    "jrb_seg7_area_1_macro_objs",
    "jrb_seg7_area_2_macro_objs",
    "lll_seg7_area_1_macro_objs",
    "lll_seg7_area_2_macro_objs",
    "pss_seg7_macro_objs",
    "rr_seg7_macro_objs",
    "sa_seg7_macro_objs",
    "sl_seg7_area_1_macro_objs",
    "sl_seg7_area_2_macro_objs",
    "ssl_seg7_area_1_macro_objs",
    "ssl_seg7_area_2_macro_objs",
    "ssl_seg7_area_3_macro_objs",
    "thi_seg7_area_1_macro_objs",
    "thi_seg7_area_2_macro_objs",
    "thi_seg7_area_3_macro_objs",
    "totwc_seg7_macro_objs",
    "ttc_seg7_macro_objs",
    "ttm_seg7_area_1_macro_objs",
    "ttm_seg7_area_2_macro_objs",
    "vcutm_seg7_macro_objs",
    "wdw_seg7_area_1_macro_objs",
    "wdw_seg7_area_2_macro_objs",
    "wf_seg7_macro_objs",
    "wmotr_seg7_macro_objs",
]

gDynosBuiltinLvlGeos = [
    "bitfs_geo_0004B0",
    "bitfs_geo_0004C8",
    "bitfs_geo_0004E0",
    "bitfs_geo_0004F8",
    "bitfs_geo_000510",
    "bitfs_geo_000528",
    "bitfs_geo_000540",
    "bitfs_geo_000558",
    "bitfs_geo_000570",
    "bitfs_geo_000588",
    "bitfs_geo_0005A0",
    "bitfs_geo_0005B8",
    "bitfs_geo_0005D0",
    "bitfs_geo_0005E8",
    "bitfs_geo_000600",
    "bitfs_geo_000618",
    "bitfs_geo_000630",
    "bitfs_geo_000648",
    "bitfs_geo_000660",
    "bitfs_geo_000678",
    "bitfs_geo_000690",
    "bitfs_geo_0006A8",
    "bitfs_geo_0006C0",
    "bitfs_geo_0006D8",
    "bitfs_geo_0006F0",
    "bitfs_geo_000708",
    "bitfs_geo_000728",
    "bitfs_geo_000740",
    "bitfs_geo_000758",
    "bitfs_geo_000770",
    "bitfs_geo_000788",
    "bitfs_geo_0007A0",
    "bits_geo_000430",
    "bits_geo_000448",
    "bits_geo_000460",
    "bits_geo_000478",
    "bits_geo_000490",
    "bits_geo_0004A8",
    "bits_geo_0004C0",
    "bits_geo_0004D8",
    "bits_geo_0004F0",
    "bits_geo_000508",
    "bits_geo_000520",
    "bits_geo_000538",
    "bits_geo_000550",
    "bits_geo_000568",
    "bits_geo_000580",
    "bits_geo_000598",
    "bits_geo_0005B0",
    "bits_geo_0005C8",
    "bits_geo_0005E0",
    "bits_geo_0005F8",
    "bits_geo_000610",
    "bits_geo_000628",
    "bits_geo_000640",
    "bits_geo_000658",
    "bits_geo_000670",
    "bits_geo_000688",
    "bits_geo_0006A0",
    "bits_geo_0006B8",
    "bits_geo_0006D0",
    "bits_geo_0006E8",
    "bits_geo_000700",
    "bits_geo_000718",
    "bob_geo_000440",
    "bob_geo_000458",
    "bob_geo_000470",
    "bob_geo_000488",
    "bowser_1_geo_0000D0",
    "bowser_2_geo_000170",
    "bowser_2_geo_000170",
    "bowser_2_geo_000188",
    "bowser_2_geo_000188",
    "bowser_3_geo_000290",
    "bowser_3_geo_000290",
    "bowser_3_geo_0002A8",
    "bowser_3_geo_0002A8",
    "bowser_3_geo_0002C0",
    "bowser_3_geo_0002C0",
    "bowser_3_geo_0002D8",
    "bowser_3_geo_0002D8",
    "bowser_3_geo_0002F0",
    "bowser_3_geo_0002F0",
    "bowser_3_geo_000308",
    "bowser_3_geo_000308",
    "bowser_3_geo_000320",
    "bowser_3_geo_000320",
    "bowser_3_geo_000338",
    "bowser_3_geo_000338",
    "bowser_3_geo_000350",
    "bowser_3_geo_000350",
    "bowser_3_geo_000368",
    "bowser_3_geo_000368",
    "bowser_3_geo_000380",
    "bowser_3_geo_000380",
    "bowser_3_geo_000398",
    "bowser_3_geo_000398",
    "castle_courtyard_geo_000200",
    "castle_courtyard_geo_000218",
    "castle_geo_000F00",
    "castle_geo_000F18",
    "castle_geo_000F30",
    "castle_geo_000F70",
    "castle_geo_000F88",
    "castle_geo_000FA8",
    "castle_geo_000FD0",
    "castle_geo_001000",
    "castle_geo_001038",
    "castle_geo_001088",
    "castle_geo_0010C8",
    "castle_geo_001110",
    "castle_geo_001158",
    "castle_geo_0011A8",
    "castle_geo_001200",
    "castle_geo_001260",
    "castle_geo_0012C8",
    "castle_geo_001348",
    "castle_geo_0013B8",
    "castle_geo_001400",
    "castle_geo_001518",
    "castle_geo_001530",
    "castle_geo_001548",
    "castle_geo_001560",
    "castle_geo_001578",
    "castle_geo_0015B8",
    "castle_geo_0015F8",
    "castle_geo_001628",
    "castle_geo_001668",
    "castle_geo_001690",
    "castle_geo_0016D8",
    "castle_geo_001740",
    "castle_geo_001798",
    "castle_geo_001800",
    "castle_geo_001858",
    "castle_geo_001940",
    "castle_geo_001958",
    "castle_geo_001980",
    "castle_geo_0019C8",
    "castle_geo_0019F8",
    "castle_geo_001A30",
    "castle_geo_001A58",
    "castle_geo_001AB8",
    "castle_geo_001AF8",
    "castle_geo_001B48",
    "castle_geo_001BB0",
    "castle_geo_001C10",
    "castle_grounds_geo_000660",
    "castle_grounds_geo_0006F4",
    "castle_grounds_geo_00070C",
    "castle_grounds_geo_000724",
    "castle_grounds_geo_00073C",
    "ccm_geo_0003D0",
    "ccm_geo_0003F0",
    "ccm_geo_00040C",
    "ccm_geo_00042C",
    "ccm_geo_00045C",
    "ccm_geo_000494",
    "ccm_geo_0004BC",
    "ccm_geo_0004E4",
    "ccm_geo_00051C",
    "ccm_geo_0005E8",
    "cotmc_geo_0001A0",
    "ddd_geo_000450",
    "ddd_geo_000478",
    "ddd_geo_0004A0",
    "ddd_geo_0004C0",
    "ddd_geo_000570",
    "geo_bbh_0005B0",
    "geo_bbh_0005C8",
    "geo_bbh_0005E0",
    "geo_bbh_0005F8",
    "geo_bbh_000610",
    "geo_bbh_000628",
    "geo_bbh_000640",
    "geo_bbh_000658",
    "geo_bbh_000670",
    "geo_bbh_0006B0",
    "geo_bbh_0006E8",
    "geo_bbh_000730",
    "geo_bbh_000750",
    "geo_bbh_000768",
    "geo_bbh_0007B0",
    "geo_bbh_0007D0",
    "geo_bbh_000800",
    "geo_bbh_000828",
    "geo_bbh_000860",
    "geo_bbh_000888",
    "geo_bbh_0008B0",
    "geo_bbh_0008E8",
    "geo_bbh_000950",
    "geo_bbh_0009C8",
    "geo_bbh_000A18",
    "geo_bbh_000A60",
    "geo_bbh_000AD8",
    "geo_bbh_000B28",
    "geo_bbh_000B88",
    "geo_bbh_000BF0",
    "geo_bbh_000C38",
    "geo_bbh_000C88",
    "geo_bbh_000CE8",
    "geo_bbh_000D20",
    "geo_bbh_000D68",
    "geo_bbh_000DB0",
    "geo_bbh_000DF0",
    "geo_bbh_000E40",
    "geo_bbh_000E80",
    "geo_bbh_000EB0",
    "geo_bbh_000F00",
    "geo_bitdw_0003C0",
    "geo_bitdw_0003D8",
    "geo_bitdw_0003F0",
    "geo_bitdw_000408",
    "geo_bitdw_000420",
    "geo_bitdw_000438",
    "geo_bitdw_000450",
    "geo_bitdw_000468",
    "geo_bitdw_000480",
    "geo_bitdw_000498",
    "geo_bitdw_0004B0",
    "geo_bitdw_0004C8",
    "geo_bitdw_0004E0",
    "geo_bitdw_0004F8",
    "geo_bitdw_000510",
    "geo_bitdw_000528",
    "geo_bitdw_000540",
    "geo_bitdw_000558",
    "geo_bitdw_000570",
    "geo_bitdw_000588",
    "geo_bitdw_0005A0",
    "geo_bitdw_0005B8",
    "geo_bitdw_0005D0",
    "geo_bitdw_0005E8",
    "geo_bitdw_000600",
    "geo_bitdw_000618",
    "hmc_geo_000530",
    "hmc_geo_000548",
    "hmc_geo_000570",
    "hmc_geo_000588",
    "hmc_geo_0005A0",
    "hmc_geo_0005B8",
    "hmc_geo_0005D0",
    "hmc_geo_0005E8",
    "hmc_geo_000618",
    "hmc_geo_000658",
    "hmc_geo_0006A8",
    "hmc_geo_0006E0",
    "hmc_geo_000700",
    "hmc_geo_000748",
    "hmc_geo_000770",
    "hmc_geo_000798",
    "hmc_geo_0007F8",
    "hmc_geo_000850",
    "hmc_geo_0008D0",
    "hmc_geo_000938",
    "hmc_geo_000998",
    "hmc_geo_000A18",
    "hmc_geo_000A88",
    "hmc_geo_000AE8",
    "hmc_geo_000B48",
    "hmc_geo_000B90",
    "jrb_geo_000900",
    "jrb_geo_000918",
    "jrb_geo_000930",
    "jrb_geo_000948",
    "jrb_geo_000960",
    "jrb_geo_000978",
    "jrb_geo_000990",
    "jrb_geo_0009B0",
    "jrb_geo_0009C8",
    "jrb_geo_0009E8",
    "jrb_geo_000A00",
    "jrb_geo_000A18",
    "jrb_geo_000AFC",
    "lll_geo_0009E0",
    "lll_geo_0009F8",
    "lll_geo_000A10",
    "lll_geo_000A28",
    "lll_geo_000A40",
    "lll_geo_000A60",
    "lll_geo_000A78",
    "lll_geo_000A90",
    "lll_geo_000AA8",
    "lll_geo_000AC0",
    "lll_geo_000AD8",
    "lll_geo_000AF0",
    "lll_geo_000B08",
    "lll_geo_000B20",
    "lll_geo_000B38",
    "lll_geo_000B50",
    "lll_geo_000B68",
    "lll_geo_000B80",
    "lll_geo_000B98",
    "lll_geo_000BB0",
    "lll_geo_000BC8",
    "lll_geo_000BE0",
    "lll_geo_000BF8",
    "lll_geo_000C10",
    "lll_geo_000C30",
    "lll_geo_000C50",
    "lll_geo_000C70",
    "lll_geo_000C90",
    "lll_geo_000CB0",
    "lll_geo_000CD0",
    "lll_geo_000CF0",
    "lll_geo_000D10",
    "lll_geo_000D30",
    "lll_geo_000D50",
    "lll_geo_000D70",
    "lll_geo_000D90",
    "lll_geo_000DB0",
    "lll_geo_000DD0",
    "lll_geo_000DE8",
    "lll_geo_000E00",
    "lll_geo_000EA8",
    "lll_geo_000EC0",
    "pss_geo_000100",
    "rr_geo_000660",
    "rr_geo_000678",
    "rr_geo_000690",
    "rr_geo_0006A8",
    "rr_geo_0006C0",
    "rr_geo_0006D8",
    "rr_geo_0006F0",
    "rr_geo_000708",
    "rr_geo_000720",
    "rr_geo_000738",
    "rr_geo_000758",
    "rr_geo_000770",
    "rr_geo_000788",
    "rr_geo_0007A0",
    "rr_geo_0007B8",
    "rr_geo_0007D0",
    "rr_geo_0007E8",
    "rr_geo_000800",
    "rr_geo_000818",
    "rr_geo_000830",
    "rr_geo_000848",
    "rr_geo_000860",
    "rr_geo_000878",
    "rr_geo_000890",
    "rr_geo_0008A8",
    "rr_geo_0008C0",
    "rr_geo_0008D8",
    "rr_geo_0008F0",
    "rr_geo_000908",
    "rr_geo_000920",
    "rr_geo_000940",
    "rr_geo_000958",
    "rr_geo_000970",
    "rr_geo_000988",
    "rr_geo_0009A0",
    "rr_geo_0009B8",
    "rr_geo_0009D0",
    "sa_geo_000170",
    "sl_geo_000360",
    "sl_geo_000378",
    "sl_geo_000390",
    "sl_geo_0003A8",
    "sl_geo_000484",
    "ssl_geo_0005C0",
    "ssl_geo_0005D8",
    "ssl_geo_000618",
    "ssl_geo_000630",
    "ssl_geo_000648",
    "ssl_geo_000734",
    "ssl_geo_000764",
    "ssl_geo_000794",
    "ssl_geo_0007AC",
    "ssl_geo_0007CC",
    "ssl_geo_00088C",
    "thi_geo_0005B0",
    "thi_geo_0005C8",
    "thi_geo_0005F0",
    "thi_geo_000608",
    "thi_geo_0006D4",
    "thi_geo_00079C",
    "totwc_geo_000160",
    "totwc_geo_000188",
    "ttc_geo_000240",
    "ttc_geo_000258",
    "ttc_geo_000270",
    "ttc_geo_000288",
    "ttc_geo_0002A8",
    "ttc_geo_0002C8",
    "ttc_geo_0002E0",
    "ttc_geo_0002F8",
    "ttc_geo_000310",
    "ttc_geo_000328",
    "ttc_geo_000340",
    "ttc_geo_000358",
    "ttc_geo_000370",
    "ttc_geo_000388",
    "ttc_geo_0003A0",
    "ttc_geo_0003B8",
    "ttm_geo_000710",
    "ttm_geo_000730",
    "ttm_geo_000748",
    "ttm_geo_000778",
    "ttm_geo_0007A8",
    "ttm_geo_0007D8",
    "ttm_geo_000808",
    "ttm_geo_000830",
    "ttm_geo_000858",
    "ttm_geo_000880",
    "ttm_geo_0008A8",
    "ttm_geo_0008D0",
    "ttm_geo_0008F8",
    "ttm_geo_000920",
    "ttm_geo_000948",
    "ttm_geo_000970",
    "ttm_geo_000990",
    "ttm_geo_0009C0",
    "ttm_geo_0009F0",
    "ttm_geo_000A18",
    "ttm_geo_000A40",
    "ttm_geo_000A70",
    "ttm_geo_000B5C",
    "ttm_geo_000BEC",
    "ttm_geo_000C84",
    "ttm_geo_000D14",
    "ttm_geo_000D4C",
    "ttm_geo_000D84",
    "ttm_geo_000DBC",
    "ttm_geo_000DF4",
    "vcutm_geo_0001F0",
    "vcutm_geo_000208",
    "wdw_geo_000580",
    "wdw_geo_000598",
    "wdw_geo_0005C0",
    "wdw_geo_0005E8",
    "wdw_geo_000610",
    "wdw_geo_000628",
    "wdw_geo_000640",
    "wdw_geo_000658",
    "wdw_geo_000724",
    "wf_geo_0007E0",
    "wf_geo_000820",
    "wf_geo_000860",
    "wf_geo_000878",
    "wf_geo_000890",
    "wf_geo_0008A8",
    "wf_geo_0008E8",
    "wf_geo_000900",
    "wf_geo_000940",
    "wf_geo_000958",
    "wf_geo_0009A0",
    "wf_geo_0009B8",
    "wf_geo_0009D0",
    "wf_geo_0009E8",
    "wf_geo_000A00",
    "wf_geo_000A40",
    "wf_geo_000A58",
    "wf_geo_000A98",
    "wf_geo_000AB0",
    "wf_geo_000AC8",
    "wf_geo_000AE0",
    "wf_geo_000AF8",
    "wf_geo_000B10",
    "wf_geo_000B38",
    "wf_geo_000B60",
    "wf_geo_000B78",
    "wf_geo_000B90",
    "wf_geo_000BA8",
    "wf_geo_000BC8",
    "wf_geo_000BE0",
    "wf_geo_000BF8",
    "wmotr_geo_0001F0",
]

gDynosBuiltinCols = [
    "bbh_seg7_collision_07026B1C",
    "bbh_seg7_collision_coffin",
    "bbh_seg7_collision_haunted_bookshelf",
    "bbh_seg7_collision_level",
    "bbh_seg7_collision_merry_go_round",
    "bbh_seg7_collision_mesh_elevator",
    "bbh_seg7_collision_staircase_step",
    "bbh_seg7_collision_tilt_floor_platform",
    "bitdw_seg7_collision_0700F688",
    "bitdw_seg7_collision_0700F70C",
    "bitdw_seg7_collision_0700F7F0",
    "bitdw_seg7_collision_0700F898",
    "bitdw_seg7_collision_0700F91C",
    "bitdw_seg7_collision_0700FA3C",
    "bitdw_seg7_collision_0700FB5C",
    "bitdw_seg7_collision_0700FC7C",
    "bitdw_seg7_collision_0700FD9C",
    "bitdw_seg7_collision_level",
    "bitdw_seg7_collision_moving_pyramid",
    "bitfs_seg7_collision_07015124",
    "bitfs_seg7_collision_07015288",
    "bitfs_seg7_collision_07015714",
    "bitfs_seg7_collision_07015768",
    "bitfs_seg7_collision_070157E0",
    "bitfs_seg7_collision_07015928",
    "bitfs_seg7_collision_inverted_pyramid",
    "bitfs_seg7_collision_level",
    "bitfs_seg7_collision_sinking_cage_platform",
    "bitfs_seg7_collision_sinking_platform",
    "bitfs_seg7_collision_squishable_platform",
    "bits_seg7_collision_0701A9A0",
    "bits_seg7_collision_0701AA0C",
    "bits_seg7_collision_0701AA84",
    "bits_seg7_collision_0701AC28",
    "bits_seg7_collision_0701ACAC",
    "bits_seg7_collision_0701AD54",
    "bits_seg7_collision_0701ADD8",
    "bits_seg7_collision_0701AE5C",
    "bits_seg7_collision_0701B0D4",
    "bits_seg7_collision_0701B26C",
    "bits_seg7_collision_0701B404",
    "bits_seg7_collision_0701B59C",
    "bits_seg7_collision_0701B734",
    "bits_seg7_collision_level",
    "bob_seg7_collision_bridge",
    "bob_seg7_collision_chain_chomp_gate",
    "bob_seg7_collision_gate",
    "bob_seg7_collision_level",
    "bowser_1_seg7_collision_level",
    "bowser_2_seg7_collision_lava",
    "bowser_2_seg7_collision_tilting_platform",
    "bowser_3_seg7_collision_07004B94",
    "bowser_3_seg7_collision_07004C18",
    "bowser_3_seg7_collision_07004C9C",
    "bowser_3_seg7_collision_07004D20",
    "bowser_3_seg7_collision_07004DA4",
    "bowser_3_seg7_collision_07004E28",
    "bowser_3_seg7_collision_07004EAC",
    "bowser_3_seg7_collision_07004F30",
    "bowser_3_seg7_collision_07004FB4",
    "bowser_3_seg7_collision_07005038",
    "bowser_3_seg7_collision_level",
    "castle_courtyard_seg7_collision",
    "castle_grounds_seg7_collision_cannon_grill",
    "castle_grounds_seg7_collision_level",
    "castle_grounds_seg7_collision_moat_grills",
    "ccm_seg7_area_1_collision",
    "ccm_seg7_area_2_collision",
    "ccm_seg7_collision_070163F8",
    "cotmc_seg7_collision_level",
    "ddd_seg7_area_1_collision",
    "ddd_seg7_area_2_collision",
    "ddd_seg7_collision_bowser_sub_door",
    "ddd_seg7_collision_submarine",
    "hmc_seg7_collision_0702B65C",
    "hmc_seg7_collision_controllable_platform_sub",
    "hmc_seg7_collision_controllable_platform",
    "hmc_seg7_collision_elevator",
    "hmc_seg7_collision_level",
    "inside_castle_seg7_area_1_collision",
    "inside_castle_seg7_area_2_collision",
    "inside_castle_seg7_area_3_collision",
    "inside_castle_seg7_collision_ddd_warp_2",
    "inside_castle_seg7_collision_ddd_warp",
    "inside_castle_seg7_collision_floor_trap",
    "inside_castle_seg7_collision_star_door",
    "inside_castle_seg7_collision_water_level_pillar",
    "jrb_seg7_area_1_collision",
    "jrb_seg7_area_2_collision",
    "jrb_seg7_collision_0700CEF0",
    "jrb_seg7_collision_0700D1DC",
    "jrb_seg7_collision_floating_box",
    "jrb_seg7_collision_floating_platform",
    "jrb_seg7_collision_in_sunken_ship_2",
    "jrb_seg7_collision_in_sunken_ship_3",
    "jrb_seg7_collision_in_sunken_ship",
    "jrb_seg7_collision_pillar_base",
    "jrb_seg7_collision_rock_solid",
    "lll_seg7_area_1_collision",
    "lll_seg7_area_2_collision",
    "lll_seg7_collision_0701D21C",
    "lll_seg7_collision_drawbridge",
    "lll_seg7_collision_falling_wall",
    "lll_seg7_collision_floating_block",
    "lll_seg7_collision_hexagonal_platform",
    "lll_seg7_collision_inverted_pyramid",
    "lll_seg7_collision_octagonal_moving_platform",
    "lll_seg7_collision_pitoune",
    "lll_seg7_collision_puzzle_piece",
    "lll_seg7_collision_rotating_fire_bars",
    "lll_seg7_collision_rotating_platform",
    "lll_seg7_collision_sinking_pyramids",
    "lll_seg7_collision_slow_tilting_platform",
    "lll_seg7_collision_wood_piece",
    "pss_seg7_collision",
    "rr_seg7_collision_07029038",
    "rr_seg7_collision_07029508",
    "rr_seg7_collision_070295F8",
    "rr_seg7_collision_0702967C",
    "rr_seg7_collision_07029750",
    "rr_seg7_collision_07029858",
    "rr_seg7_collision_07029924",
    "rr_seg7_collision_07029C1C",
    "rr_seg7_collision_07029FA4",
    "rr_seg7_collision_0702A32C",
    "rr_seg7_collision_0702A6B4",
    "rr_seg7_collision_donut_platform",
    "rr_seg7_collision_elevator_platform",
    "rr_seg7_collision_level",
    "rr_seg7_collision_pendulum",
    "rr_seg7_collision_rotating_platform_with_fire",
    "sa_seg7_collision",
    "sl_seg7_area_1_collision",
    "sl_seg7_area_2_collision",
    "sl_seg7_collision_pound_explodes",
    "sl_seg7_collision_sliding_snow_mound",
    "ssl_seg7_area_1_collision",
    "ssl_seg7_area_2_collision",
    "ssl_seg7_area_3_collision",
    "ssl_seg7_collision_0702808C",
    "ssl_seg7_collision_07028274",
    "ssl_seg7_collision_070282F8",
    "ssl_seg7_collision_07028370",
    "ssl_seg7_collision_070284B0",
    "ssl_seg7_collision_grindel",
    "ssl_seg7_collision_pyramid_elevator",
    "ssl_seg7_collision_pyramid_top",
    "ssl_seg7_collision_spindel",
    "ssl_seg7_collision_tox_box",
    "thi_seg7_area_1_collision",
    "thi_seg7_area_2_collision",
    "thi_seg7_area_3_collision",
    "thi_seg7_collision_top_trap",
    "totwc_seg7_collision",
    "ttc_seg7_collision_07014F70",
    "ttc_seg7_collision_07015008",
    "ttc_seg7_collision_070152B4",
    "ttc_seg7_collision_070153E0",
    "ttc_seg7_collision_07015584",
    "ttc_seg7_collision_07015650",
    "ttc_seg7_collision_07015754",
    "ttc_seg7_collision_070157D8",
    "ttc_seg7_collision_clock_main_rotation",
    "ttc_seg7_collision_clock_pendulum",
    "ttc_seg7_collision_clock_platform",
    "ttc_seg7_collision_level",
    "ttc_seg7_collision_rotating_clock_platform2",
    "ttc_seg7_collision_sliding_surface",
    "ttm_seg7_area_1_collision",
    "ttm_seg7_area_2_collision",
    "ttm_seg7_area_3_collision",
    "ttm_seg7_area_4_collision",
    "ttm_seg7_collision_pitoune_2",
    "ttm_seg7_collision_podium_warp",
    "ttm_seg7_collision_ukiki_cage",
    "vcutm_seg7_collision_0700AC44",
    "vcutm_seg7_collision",
    "wdw_seg7_area_1_collision",
    "wdw_seg7_area_2_collision",
    "wdw_seg7_collision_070184C8",
    "wdw_seg7_collision_07018528",
    "wdw_seg7_collision_070186B4",
    "wdw_seg7_collision_arrow_lift",
    "wdw_seg7_collision_express_elevator_platform",
    "wdw_seg7_collision_rect_floating_platform",
    "wdw_seg7_collision_square_floating_platform",
    "wf_seg7_collision_070102D8",
    "wf_seg7_collision_breakable_wall_2",
    "wf_seg7_collision_breakable_wall",
    "wf_seg7_collision_bullet_bill_cannon",
    "wf_seg7_collision_clocklike_rotation",
    "wf_seg7_collision_kickable_board",
    "wf_seg7_collision_large_bomp",
    "wf_seg7_collision_platform",
    "wf_seg7_collision_rotating_platform",
    "wf_seg7_collision_sliding_brick_platform",
    "wf_seg7_collision_small_bomp",
    "wf_seg7_collision_tower_door",
    "wf_seg7_collision_tower",
    "wf_seg7_collision_trapezoid",
    "wf_seg7_collision_tumbling_bridge",
    "wmotr_seg7_collision",
    "bbh_seg7_collision_coffin",
    "bbh_seg7_collision_haunted_bookshelf",
    "bbh_seg7_collision_merry_go_round",
    "bbh_seg7_collision_mesh_elevator",
    "bbh_seg7_collision_staircase_step",
    "bbh_seg7_collision_tilt_floor_platform",
    "bitdw_seg7_collision_moving_pyramid",
    "bitfs_seg7_collision_inverted_pyramid",
    "bitfs_seg7_collision_sinking_cage_platform",
    "bitfs_seg7_collision_sinking_platform",
    "bitfs_seg7_collision_squishable_platform",
    "blue_coin_switch_seg8_collision_08000E98",
    "bob_seg7_collision_chain_chomp_gate",
    "bowser_2_seg7_collision_tilting_platform",
    "breakable_box_seg8_collision_08012D70",
    "cannon_lid_seg8_collision_08004950",
    "capswitch_collision_050033D0",
    "capswitch_collision_05003448",
    "castle_grounds_seg7_collision_cannon_grill",
    "castle_grounds_seg7_collision_moat_grills",
    "checkerboard_platform_seg8_collision_0800D710",
    "ddd_seg7_collision_bowser_sub_door",
    "ddd_seg7_collision_submarine",
    "door_seg3_collision_0301CE78",
    "dorrie_seg6_collision_0600F644",
    "dorrie_seg6_collision_0600FBB8",
    "exclamation_box_outline_seg8_collision_08025F78",
    "hmc_seg7_collision_controllable_platform",
    "hmc_seg7_collision_controllable_platform_sub",
    "hmc_seg7_collision_elevator",
    "inside_castle_seg7_collision_floor_trap",
    "inside_castle_seg7_collision_star_door",
    "inside_castle_seg7_collision_water_level_pillar",
    "jrb_seg7_collision_floating_box",
    "jrb_seg7_collision_floating_platform",
    "jrb_seg7_collision_in_sunken_ship",
    "jrb_seg7_collision_in_sunken_ship_2",
    "jrb_seg7_collision_in_sunken_ship_3",
    "jrb_seg7_collision_pillar_base",
    "jrb_seg7_collision_rock_solid",
    "lll_hexagonal_mesh_seg3_collision_0301CECC",
    "lll_seg7_collision_drawbridge",
    "lll_seg7_collision_falling_wall",
    "lll_seg7_collision_floating_block",
    "lll_seg7_collision_hexagonal_platform",
    "lll_seg7_collision_inverted_pyramid",
    "lll_seg7_collision_octagonal_moving_platform",
    "lll_seg7_collision_pitoune",
    "lll_seg7_collision_puzzle_piece",
    "lll_seg7_collision_rotating_fire_bars",
    "lll_seg7_collision_rotating_platform",
    "lll_seg7_collision_sinking_pyramids",
    "lll_seg7_collision_slow_tilting_platform",
    "lll_seg7_collision_wood_piece",
    "metal_box_seg8_collision_08024C28",
    "penguin_seg5_collision_05008B88",
    "poundable_pole_collision_06002490",
    "purple_switch_seg8_collision_0800C7A8",
    "rr_seg7_collision_donut_platform",
    "rr_seg7_collision_elevator_platform",
    "rr_seg7_collision_pendulum",
    "rr_seg7_collision_rotating_platform_with_fire",
    "sl_seg7_collision_pound_explodes",
    "sl_seg7_collision_sliding_snow_mound",
    "springboard_collision_05001A28",
    "ssl_seg7_collision_0702808C",
    "ssl_seg7_collision_grindel",
    "ssl_seg7_collision_pyramid_elevator",
    "ssl_seg7_collision_pyramid_top",
    "ssl_seg7_collision_spindel",
    "ssl_seg7_collision_tox_box",
    "thi_seg7_collision_top_trap",
    "thwomp_seg5_collision_0500B7D0",
    "thwomp_seg5_collision_0500B92C",
    "ttc_seg7_collision_clock_main_rotation",
    "ttc_seg7_collision_clock_pendulum",
    "ttc_seg7_collision_clock_platform",
    "ttc_seg7_collision_rotating_clock_platform2",
    "ttc_seg7_collision_sliding_surface",
    "ttm_seg7_collision_pitoune_2",
    "ttm_seg7_collision_podium_warp",
    "ttm_seg7_collision_ukiki_cage",
    "unknown_seg8_collision_080262F8",
    "warp_pipe_seg3_collision_03009AC8",
    "wdw_seg7_collision_arrow_lift",
    "wdw_seg7_collision_express_elevator_platform",
    "wdw_seg7_collision_rect_floating_platform",
    "wdw_seg7_collision_square_floating_platform",
    "wf_seg7_collision_breakable_wall",
    "wf_seg7_collision_breakable_wall_2",
    "wf_seg7_collision_bullet_bill_cannon",
    "wf_seg7_collision_clocklike_rotation",
    "wf_seg7_collision_kickable_board",
    "wf_seg7_collision_large_bomp",
    "wf_seg7_collision_platform",
    "wf_seg7_collision_sliding_brick_platform",
    "wf_seg7_collision_small_bomp",
    "wf_seg7_collision_tower",
    "wf_seg7_collision_tower_door",
    "whomp_seg6_collision_06020A0C",
    "wooden_signpost_seg3_collision_0302DD80",
]

gDynosBuiltinAnims = [
    "amp_seg8_anims_08004034",
    "bobomb_seg8_anims_0802396C",
    "chuckya_seg8_anims_0800C070",
    "flyguy_seg8_anims_08011A64",
    "goomba_seg8_anims_0801DA4C",
    "blue_fish_seg3_anims_0301C2B0",
    "bowser_key_seg3_anims_list",
    "butterfly_seg3_anims_030056B0",
    "door_seg3_anims_030156C0",
    "heave_ho_seg5_anims_0501534C",
    "hoot_seg5_anims_05005768",
    "blargg_seg5_anims_0500616C",
    "bully_seg5_anims_0500470C",
    "king_bobomb_seg5_anims_0500FE30",
    "clam_shell_seg5_anims_05001744",
    "manta_seg5_anims_05008EB4",
    "sushi_seg5_anims_0500AE54",
    "unagi_seg5_anims_05012824",
    "eyerok_seg5_anims_050116E4",
    "klepto_seg5_anims_05008CFC",
    "monty_mole_seg5_anims_05007248",
    "ukiki_seg5_anims_05015784",
    "penguin_seg5_anims_05008B74",
    "snowman_seg5_anims_0500D118",
    "spindrift_seg5_anims_05002D68",
    "bookend_seg5_anims_05002540",
    "chair_seg5_anims_05005784",
    "mad_piano_seg5_anims_05009B14",
    "birds_seg5_anims_050009E8",
    "peach_seg5_anims_0501C41C",
    "yoshi_seg5_anims_05024100",
    "lakitu_enemy_seg5_anims_050144D4",
    "spiny_seg5_anims_05016EAC",
    "spiny_egg_seg5_anims_050157E4",
    "wiggler_seg5_anims_0500C874",
    "wiggler_seg5_anims_0500EC8C",
    "bowser_seg6_anims_06057690",
    "bub_seg6_anims_06012354",
    "cyan_fish_seg6_anims_0600E264",
    "seaweed_seg6_anims_0600A4D4",
    "skeeter_seg6_anims_06007DE0",
    "water_ring_seg6_anims_06013F7C",
    "chain_chomp_seg6_anims_06025178",
    "koopa_seg6_anims_06011364",
    "koopa_flag_seg6_anims_06001028",
    "piranha_plant_seg6_anims_0601C31C",
    "whomp_seg6_anims_06020A04",
    "lakitu_seg6_anims_060058F8",
    "mips_seg6_anims_06015634",
    "toad_seg6_anims_0600FB58",
    "chilly_chief_seg6_anims_06003994",
    "moneybag_seg6_anims_06005E5C",
    "dorrie_seg6_anims_0600F638",
    "scuttlebug_seg6_anims_06015064",
    "swoop_seg6_anims_060070D0",
    "castle_grounds_seg7_anims_flags",
]

gDynosBuiltinFuncs = [
    {"name": "geo_mirror_mario_set_alpha", "type": "FUNCTION_GEO"},
    {"name": "geo_switch_mario_stand_run", "type": "FUNCTION_GEO"},
    {"name": "geo_switch_mario_eyes", "type": "FUNCTION_GEO"},
    {"name": "geo_mario_tilt_torso", "type": "FUNCTION_GEO"},
    {"name": "geo_mario_head_rotation", "type": "FUNCTION_GEO"},
    {"name": "geo_switch_mario_hand", "type": "FUNCTION_GEO"},
    {"name": "geo_mario_hand_foot_scaler", "type": "FUNCTION_GEO"},
    {"name": "geo_switch_mario_cap_effect", "type": "FUNCTION_GEO"},
    {"name": "geo_switch_mario_cap_on_off", "type": "FUNCTION_GEO"},
    {"name": "geo_mario_rotate_wing_cap_wings", "type": "FUNCTION_GEO"},
    {"name": "geo_switch_mario_hand_grab_pos", "type": "FUNCTION_GEO"},
    {"name": "geo_render_mirror_mario", "type": "FUNCTION_GEO"},
    {"name": "geo_mirror_mario_backface_culling", "type": "FUNCTION_GEO"},
    {"name": "geo_update_projectile_pos_from_parent", "type": "FUNCTION_GEO"},
    {"name": "geo_update_layer_transparency", "type": "FUNCTION_GEO"},
    {"name": "geo_switch_anim_state", "type": "FUNCTION_GEO"},
    {"name": "geo_switch_area", "type": "FUNCTION_GEO"},
    {"name": "geo_camera_main", "type": "FUNCTION_GEO"},
    {"name": "geo_camera_fov", "type": "FUNCTION_GEO"},
    {"name": "geo_envfx_main", "type": "FUNCTION_GEO"},
    {"name": "geo_skybox_main", "type": "FUNCTION_GEO"},
    {"name": "geo_wdw_set_initial_water_level", "type": "FUNCTION_GEO"},
    {"name": "geo_movtex_pause_control", "type": "FUNCTION_GEO"},
    {"name": "geo_movtex_draw_water_regions", "type": "FUNCTION_GEO"},
    {"name": "geo_movtex_draw_nocolor", "type": "FUNCTION_GEO"},
    {"name": "geo_movtex_draw_colored", "type": "FUNCTION_GEO"},
    {"name": "geo_movtex_draw_colored_no_update", "type": "FUNCTION_GEO"},
    {"name": "geo_movtex_draw_colored_2_no_update", "type": "FUNCTION_GEO"},
    {"name": "geo_movtex_update_horizontal", "type": "FUNCTION_GEO"},
    {"name": "geo_movtex_draw_colored_no_update", "type": "FUNCTION_GEO"},
    {"name": "geo_painting_draw", "type": "FUNCTION_GEO"},
    {"name": "geo_painting_update", "type": "FUNCTION_GEO"},
    {"name": "geo_exec_inside_castle_light", "type": "FUNCTION_GEO"},
    {"name": "geo_exec_flying_carpet_timer_update", "type": "FUNCTION_GEO"},
    {"name": "geo_exec_flying_carpet_create", "type": "FUNCTION_GEO"},
    {"name": "geo_exec_cake_end_screen", "type": "FUNCTION_GEO"},
    {"name": "geo_cannon_circle_base", "type": "FUNCTION_GEO"},
    {"name": "geo_move_mario_part_from_parent", "type": "FUNCTION_GEO"},
    {"name": "geo_bits_bowser_coloring", "type": "FUNCTION_GEO"},
    {"name": "geo_update_body_rot_from_parent", "type": "FUNCTION_GEO"},
    {"name": "geo_switch_bowser_eyes", "type": "FUNCTION_GEO"},
    {"name": "geo_switch_tuxie_mother_eyes", "type": "FUNCTION_GEO"},
    {"name": "geo_update_held_mario_pos", "type": "FUNCTION_GEO"},
    {"name": "geo_snufit_move_mask", "type": "FUNCTION_GEO"},
    {"name": "geo_snufit_scale_body", "type": "FUNCTION_GEO"},
    {"name": "geo_scale_bowser_key", "type": "FUNCTION_GEO"},
    {"name": "geo_offset_klepto_held_object", "type": "FUNCTION_GEO"},
    {"name": "geo_switch_peach_eyes", "type": "FUNCTION_GEO"},
    {"name": "geo_mario_set_player_colors", "type": "FUNCTION_GEO"},
    {"name": "geo_movtex_draw_water_regions_ext", "type": "FUNCTION_GEO"},
    {"name": "lvl_init_or_update", "type": "FUNCTION_LVL"},
    {"name": "geo_choose_area_ext", "type": "FUNCTION_GEO"},
    {"name": "bhv_cap_switch_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_tiny_star_particles_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_grindel_thwomp_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_koopa_shell_underwater_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_door_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_door_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_star_door_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_star_door_loop_2", "type": "FUNCTION_BHV"},
    {"name": "bhv_mr_i_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_mr_i_body_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_mr_i_particle_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_piranha_particle_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_giant_pole_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_pole_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_pole_base_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_thi_huge_island_top_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_thi_tiny_island_top_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_king_bobomb_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_bobomb_anchor_mario_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_beta_chest_bottom_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_beta_chest_bottom_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_beta_chest_lid_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_bubble_wave_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_bubble_maybe_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_bubble_player_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_water_air_bubble_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_water_air_bubble_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_particle_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_particle_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_water_waves_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_small_bubbles_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_fish_group_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_cannon_base_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_cannon_barrel_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_cannon_base_unused_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_chuckya_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_chuckya_anchor_mario_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_rotating_platform_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_wf_breakable_wall_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_kickable_board_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_tower_door_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_wf_rotating_wooden_platform_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_wf_rotating_wooden_platform_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_fading_warp_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_warp_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_white_puff_exploding_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_spawned_star_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_spawned_star_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_coin_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_coin_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_coin_inside_boo_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_coin_formation_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_coin_formation_spawn_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_coin_formation_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_temp_coin_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_coin_sparkles_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_golden_coin_sparkles_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_wall_tiny_star_particle_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_pound_tiny_star_particle_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_pound_tiny_star_particle_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_punch_tiny_triangle_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_punch_tiny_triangle_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_tumbling_bridge_platform_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_tumbling_bridge_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_elevator_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_elevator_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_water_mist_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_water_mist_spawn_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_water_mist_2_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_pound_white_puffs_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_ground_sand_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_ground_snow_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_wind_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_unused_particle_spawn_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_ukiki_cage_star_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_ukiki_cage_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_bitfs_sinking_platform_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_bitfs_sinking_cage_platform_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_ddd_moving_pole_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_platform_normals_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_tilting_inverted_pyramid_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_squishable_platform_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_beta_moving_flames_spawn_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_beta_moving_flames_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_rr_rotating_bridge_platform_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_flamethrower_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_flamethrower_flame_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_bouncing_fireball_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_bouncing_fireball_flame_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_bowser_shock_wave_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_flame_mario_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_black_smoke_mario_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_black_smoke_bowser_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_black_smoke_upward_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_beta_fish_splash_spawner_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_spindrift_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_tower_platform_group_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_tower_platform_group_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_wf_sliding_tower_platform_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_wf_elevator_tower_platform_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_wf_solid_tower_platform_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_snow_leaf_particle_spawn_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_tree_snow_or_leaf_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_piranha_plant_bubble_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_piranha_plant_waking_bubbles_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_purple_switch_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_hidden_object_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_breakable_box_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_pushable_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_init_room", "type": "FUNCTION_BHV"},
    {"name": "bhv_small_water_wave_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_yellow_coin_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_yellow_coin_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_squarish_path_moving_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_squarish_path_parent_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_squarish_path_parent_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_heave_ho_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_heave_ho_throw_mario_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_ccm_touched_star_spawn_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_unused_poundable_platform", "type": "FUNCTION_BHV"},
    {"name": "bhv_beta_trampoline_top_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_beta_trampoline_spring_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_jumping_box_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_boo_cage_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_boo_cage_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_bowser_key_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_bowser_key_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_grand_star_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_grand_star_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_beta_boo_key_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_alpha_boo_key_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_bullet_bill_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_bullet_bill_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_white_puff_smoke_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_bowser_tail_anchor_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_bowser_tail_anchor_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_bowser_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_bowser_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_bowser_body_anchor_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_bowser_body_anchor_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_bowser_flame_spawn_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_tilting_bowser_lava_platform_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_falling_bowser_platform_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_blue_bowser_flame_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_blue_bowser_flame_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_flame_floating_landing_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_flame_floating_landing_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_blue_flames_group_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_flame_bouncing_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_flame_bouncing_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_flame_moving_forward_growing_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_flame_moving_forward_growing_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_flame_bowser_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_flame_bowser_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_flame_large_burning_out_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_blue_fish_movement_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_tank_fish_group_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_checkerboard_elevator_group_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_checkerboard_elevator_group_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_checkerboard_platform_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_checkerboard_platform_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_bowser_key_unlock_door_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_bowser_key_course_exit_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_invisible_objects_under_bridge_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_invisible_objects_under_bridge_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_water_level_pillar_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_water_level_pillar_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_ddd_warp_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_moat_grills_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_rotating_clock_arm_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_ukiki_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_ukiki_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_lll_sinking_rock_block_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_lll_moving_octagonal_mesh_platform_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_lll_rotating_block_fire_bars_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_lll_rotating_hex_flame_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_lll_wood_piece_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_lll_floating_wood_bridge_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_volcano_flames_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_lll_rotating_hexagonal_ring_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_lll_sinking_rectangular_platform_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_lll_sinking_square_platforms_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_koopa_shell_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_koopa_shell_flame_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_tox_box_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_piranha_plant_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_lll_bowser_puzzle_piece_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_lll_bowser_puzzle_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_tuxies_mother_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_small_penguin_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_fish_spawner_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_fish_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_wdw_express_elevator_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_bub_spawner_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_bub_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_exclamation_box_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_exclamation_box_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_rotating_exclamation_box_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_sound_spawner_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_bowsers_sub_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_sushi_shark_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_sushi_shark_collision_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_jrb_sliding_box_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_ship_part_3_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_sunken_ship_part_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_white_puff_1_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_white_puff_2_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_blue_coin_switch_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_hidden_blue_coin_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_openable_cage_door_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_openable_grill_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_water_level_diamond_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_init_changing_water_level_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_tweester_sand_particle_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_tweester_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_merry_go_round_boo_manager_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_animated_texture_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_boo_in_castle_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_boo_with_cage_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_boo_with_cage_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_boo_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_big_boo_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_courtyard_boo_triplet_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_boo_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_boo_boss_spawned_bridge_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_bbh_tilting_trap_platform_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_haunted_bookshelf_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_merry_go_round_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_play_music_track_when_touched_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_beta_bowser_anchor_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_static_checkered_platform_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_castle_floor_trap_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_castle_floor_trap_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_floor_trap_in_castle_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_sparkle_spawn_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_scuttlebug_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_scuttlebug_spawn_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_whomp_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_water_splash_spawn_droplets", "type": "FUNCTION_BHV"},
    {"name": "bhv_water_droplet_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_water_droplet_splash_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_bubble_splash_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_idle_water_wave_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_shallow_water_splash_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_wave_trail_shrink", "type": "FUNCTION_BHV"},
    {"name": "bhv_strong_wind_particle_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_sl_snowman_wind_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_sl_walking_penguin_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_menu_button_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_menu_button_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_menu_button_manager_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_menu_button_manager_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_act_selector_star_type_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_act_selector_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_act_selector_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_moving_yellow_coin_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_moving_yellow_coin_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_moving_blue_coin_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_moving_blue_coin_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_blue_coin_sliding_jumping_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_blue_coin_sliding_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_blue_coin_jumping_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_seaweed_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_seaweed_bundle_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_bobomb_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_bobomb_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_bobomb_fuse_smoke_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_bobomb_buddy_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_bobomb_buddy_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_cannon_closed_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_cannon_closed_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_whirlpool_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_whirlpool_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_jet_stream_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_homing_amp_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_homing_amp_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_circling_amp_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_circling_amp_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_butterfly_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_butterfly_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_hoot_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_hoot_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_beta_holdable_object_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_beta_holdable_object_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_object_bubble_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_object_bubble_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_object_water_wave_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_object_water_wave_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_explosion_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_explosion_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_bobomb_bully_death_smoke_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_bobomb_explosion_bubble_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_bobomb_explosion_bubble_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_respawner_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_small_bully_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_bully_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_big_bully_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_big_bully_with_minions_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_big_bully_with_minions_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_jet_stream_ring_spawner_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_jet_stream_water_ring_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_jet_stream_water_ring_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_manta_ray_water_ring_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_manta_ray_water_ring_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_bowser_bomb_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_bowser_bomb_explosion_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_bowser_bomb_smoke_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_celebration_star_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_celebration_star_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_celebration_star_sparkle_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_star_key_collection_puff_spawner_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_lll_drawbridge_spawner_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_lll_drawbridge_spawner_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_lll_drawbridge_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_small_bomp_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_small_bomp_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_large_bomp_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_large_bomp_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_wf_sliding_platform_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_wf_sliding_platform_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_moneybag_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_moneybag_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_moneybag_hidden_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_bob_pit_bowling_ball_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_bob_pit_bowling_ball_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_free_bowling_ball_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_free_bowling_ball_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_bowling_ball_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_bowling_ball_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_generic_bowling_ball_spawner_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_generic_bowling_ball_spawner_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_thi_bowling_ball_spawner_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_rr_cruiser_wing_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_rr_cruiser_wing_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_spindel_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_spindel_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_ssl_moving_pyramid_wall_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_ssl_moving_pyramid_wall_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_pyramid_elevator_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_pyramid_elevator_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_pyramid_elevator_trajectory_marker_ball_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_pyramid_top_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_pyramid_top_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_pyramid_top_fragment_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_pyramid_top_fragment_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_pyramid_pillar_touch_detector_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_waterfall_sound_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_volcano_sound_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_castle_flag_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_birds_sound_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_ambient_sounds_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_sand_sound_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_castle_cannon_grate_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_snowmans_bottom_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_snowmans_bottom_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_snowmans_head_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_snowmans_head_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_snowmans_body_checkpoint_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_big_boulder_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_big_boulder_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_big_boulder_generator_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_wing_cap_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_wing_vanish_cap_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_metal_cap_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_metal_cap_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_normal_cap_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_normal_cap_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_vanish_cap_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_collect_star_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_collect_star_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_star_spawn_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_star_spawn_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_hidden_red_coin_star_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_hidden_red_coin_star_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_red_coin_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_red_coin_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_bowser_course_red_coin_star_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_hidden_star_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_hidden_star_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_hidden_star_trigger_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_ttm_rolling_log_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_rolling_log_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_lll_rolling_log_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_1up_common_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_1up_walking_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_1up_running_away_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_1up_sliding_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_1up_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_1up_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_1up_jump_on_approach_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_1up_hidden_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_1up_hidden_trigger_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_1up_hidden_in_pole_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_1up_hidden_in_pole_trigger_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_1up_hidden_in_pole_spawner_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_controllable_platform_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_controllable_platform_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_controllable_platform_sub_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_breakable_box_small_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_breakable_box_small_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_sliding_snow_mound_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_snow_mound_spawn_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_floating_platform_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_arrow_lift_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_orange_number_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_orange_number_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_manta_ray_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_manta_ray_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_falling_pillar_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_falling_pillar_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_falling_pillar_hitbox_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_jrb_floating_box_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_decorative_pendulum_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_decorative_pendulum_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_treasure_chest_ship_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_treasure_chest_ship_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_treasure_chest_jrb_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_treasure_chest_jrb_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_treasure_chest_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_treasure_chest_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_treasure_chest_bottom_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_treasure_chest_bottom_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_treasure_chest_top_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_mips_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_mips_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_yoshi_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_koopa_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_koopa_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_koopa_race_endpoint_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_pokey_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_pokey_body_part_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_swoop_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_fly_guy_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_goomba_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_goomba_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_goomba_triplet_spawner_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_chain_chomp_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_chain_chomp_chain_part_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_wooden_post_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_chain_chomp_gate_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_chain_chomp_gate_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_wiggler_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_wiggler_body_part_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_enemy_lakitu_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_camera_lakitu_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_camera_lakitu_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_cloud_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_cloud_part_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_spiny_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_monty_mole_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_monty_mole_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_monty_mole_hole_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_monty_mole_rock_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_platform_on_track_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_platform_on_track_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_track_ball_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_seesaw_platform_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_seesaw_platform_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_ferris_wheel_axle_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_ferris_wheel_platform_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_water_bomb_spawner_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_water_bomb_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_water_bomb_shadow_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_ttc_rotating_solid_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_ttc_rotating_solid_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_ttc_pendulum_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_ttc_pendulum_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_ttc_treadmill_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_ttc_treadmill_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_ttc_moving_bar_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_ttc_moving_bar_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_ttc_cog_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_ttc_cog_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_ttc_pit_block_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_ttc_pit_block_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_ttc_elevator_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_ttc_elevator_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_ttc_2d_rotator_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_ttc_2d_rotator_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_ttc_spinner_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_mr_blizzard_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_mr_blizzard_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_mr_blizzard_snowball", "type": "FUNCTION_BHV"},
    {"name": "bhv_sliding_plat_2_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_sliding_plat_2_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_rotating_octagonal_plat_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_rotating_octagonal_plat_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_animates_on_floor_switch_press_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_animates_on_floor_switch_press_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_activated_back_and_forth_platform_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_activated_back_and_forth_platform_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_recovery_heart_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_water_bomb_cannon_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_bubble_cannon_barrel_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_unagi_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_unagi_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_unagi_subobject_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_dorrie_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_haunted_chair_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_haunted_chair_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_mad_piano_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_flying_bookend_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_bookend_spawn_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_haunted_bookshelf_manager_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_book_switch_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_fire_piranha_plant_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_fire_piranha_plant_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_small_piranha_flame_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_fire_spitter_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_fly_guy_flame_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_snufit_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_snufit_balls_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_horizontal_grindel_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_horizontal_grindel_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_eyerok_boss_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_eyerok_boss_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_eyerok_hand_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_klepto_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_klepto_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_bird_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_racing_penguin_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_racing_penguin_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_penguin_race_finish_line_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_penguin_race_shortcut_check_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_coffin_spawner_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_coffin_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_clam_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_skeeter_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_skeeter_wave_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_swing_platform_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_swing_platform_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_donut_platform_spawner_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_donut_platform_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_ddd_pole_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_ddd_pole_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_red_coin_star_marker_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_triplet_butterfly_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_bubba_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_intro_lakitu_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_intro_peach_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_end_birds_1_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_end_birds_2_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_intro_scene_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_dust_smoke_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_yoshi_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_volcano_trap_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_toad_message_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_toad_message_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_unlock_door_star_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_unlock_door_star_loop", "type": "FUNCTION_BHV"},
    {"name": "load_object_collision_model", "type": "FUNCTION_BHV"},
    {"name": "obj_set_secondary_camera_focus", "type": "FUNCTION_BHV"},
    {"name": "lvl_intro_update", "type": "FUNCTION_LVL"},
    {"name": "geo_intro_super_mario_64_logo", "type": "FUNCTION_GEO"},
    {"name": "geo_intro_tm_copyright", "type": "FUNCTION_GEO"},
    {"name": "geo_intro_regular_backdrop", "type": "FUNCTION_GEO"},
    {"name": "geo_draw_mario_head_goddard", "type": "FUNCTION_GEO"},
    {"name": "bhv_blue_coin_number_loop", "type": "FUNCTION_BHV"},
    {"name": "bhv_blue_coin_switch_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_star_number_loop", "type": "FUNCTION_BHV"},
    {"name": "spawn_star_number", "type": "FUNCTION_BHV"},
    {"name": "bhv_ferris_wheel_platform_init", "type": "FUNCTION_BHV"},
    {"name": "geo_mario_cap_display_list", "type": "FUNCTION_GEO"},
    {"name": "bhv_ambient_light_update", "type": "FUNCTION_BHV"},
    {"name": "bhv_point_light_init", "type": "FUNCTION_BHV"},
    {"name": "bhv_point_light_loop", "type": "FUNCTION_BHV"},
    {"name": "geo_rotate_coin", "func_ptr": "geo_rotate_3d_coin", "type": "FUNCTION_GEO"},
]

gDynosBuiltinActors = [
    "amp_geo",
    "birds_geo",
    "blargg_geo",
    "blue_coin_switch_geo",
    "black_bobomb_geo",
    "bobomb_buddy_geo",
    "boo_geo",
    "boo_castle_geo",
    "bookend_geo",
    "bookend_part_geo",
    "bowling_ball_geo",
    "bowling_ball_track_geo",
    "bowser_geo",
    "bowser2_geo",
    "bowser_bomb_geo",
    "bowser_flames_geo",
    "bowser_impact_smoke_geo",
    "bowser_1_yellow_sphere_geo",
    "invisible_bowser_accessory_geo",
    "bowser_key_geo",
    "bowser_key_cutscene_geo",
    "breakable_box_geo",
    "breakable_box_small_geo",
    "bub_geo",
    "bubba_geo",
    "bubble_geo",
    "bullet_bill_geo",
    "bully_geo",
    "bully_boss_geo",
    "burn_smoke_geo",
    "butterfly_geo",
    "cannon_barrel_geo",
    "cannon_base_geo",
    "cap_switch_geo",
    "cartoon_star_geo",
    "chain_chomp_geo",
    "checkerboard_platform_geo",
    "chilly_chief_geo",
    "chilly_chief_big_geo",
    "chuckya_geo",
    "clam_shell_geo",
    "yellow_coin_geo",
    "yellow_coin_no_shadow_geo",
    "blue_coin_geo",
    "blue_coin_no_shadow_geo",
    "red_coin_geo",
    "red_coin_no_shadow_geo",
    "dirt_animation_geo",
    "dorrie_geo",
    "cabin_door_geo",
    "castle_door_geo",
    "castle_door_0_star_geo",
    "castle_door_1_star_geo",
    "castle_door_3_stars_geo",
    "haunted_door_geo",
    "hazy_maze_door_geo",
    "metal_door_geo",
    "key_door_geo",
    "wooden_door_geo",
    "enemy_lakitu_geo",
    "exclamation_box_geo",
    "exclamation_box_outline_geo",
    "explosion_geo",
    "eyerok_left_hand_geo",
    "eyerok_right_hand_geo",
    "fish_geo",
    "cyan_fish_geo",
    "flyguy_geo",
    "red_flame_geo",
    "red_flame_shadow_geo",
    "blue_flame_geo",
    "fwoosh_geo",
    "goomba_geo",
    "haunted_cage_geo",
    "haunted_chair_geo",
    "heart_geo",
    "heave_ho_geo",
    "hoot_geo",
    "king_bobomb_geo",
    "klepto_geo",
    "koopa_with_shell_geo",
    "koopa_without_shell_geo",
    "koopa_flag_geo",
    "koopa_shell_geo",
    "lakitu_geo",
    "mad_piano_geo",
    "manta_seg5_geo_05008D14",
    "mario_geo",
    "marios_cap_geo",
    "marios_metal_cap_geo",
    "marios_wing_cap_geo",
    "marios_winged_metal_cap_geo",
    "metal_box_geo",
    "metallic_ball_geo",
    "mips_geo",
    "mist_geo",
    "moneybag_geo",
    "monty_mole_geo",
    "mr_blizzard_geo",
    "mr_blizzard_hidden_geo",
    "mr_i_geo",
    "mr_i_iris_geo",
    "mushroom_1up_geo",
    "number_geo",
    "peach_geo",
    "penguin_geo",
    "piranha_plant_geo",
    "pokey_head_geo",
    "pokey_body_part_geo",
    "purple_marble_geo",
    "purple_switch_geo",
    "scuttlebug_geo",
    "seaweed_geo",
    "skeeter_geo",
    "small_key_geo",
    "small_water_splash_geo",
    "smoke_geo",
    "snufit_geo",
    "sparkles_geo",
    "sparkles_animation_geo",
    "spindrift_geo",
    # "spiny_geo",
    "spiny_ball_geo",
    "star_geo",
    "transparent_star_geo",
    "sushi_geo",
    "swoop_geo",
    "thwomp_geo",
    "toad_geo",
    "treasure_chest_base_geo",
    "treasure_chest_lid_geo",
    "bubbly_tree_geo",
    "spiky_tree_geo",
    "snow_tree_geo",
    "palm_tree_geo",
    "leaves_geo",
    "tweester_geo",
    "ukiki_geo",
    "unagi_geo",
    "warp_pipe_geo",
    "water_bomb_geo",
    "water_bomb_shadow_geo",
    "water_ring_geo",
    "water_splash_geo",
    "idle_water_wave_geo",
    "wave_trail_geo",
    "white_particle_geo",
    "white_puff_geo",
    "whomp_geo",
    "wiggler_head_geo",
    "wiggler_body_geo",
    "wooden_post_geo",
    "wooden_signpost_geo",
    "yellow_sphere_geo",
    "yoshi_geo",
    "yoshi_egg_geo",
    # coop models
    "error_model_geo",
    "luigi_geo",
    "luigis_cap_geo",
    "luigis_metal_cap_geo",
    "luigis_wing_cap_geo",
    "luigis_winged_metal_cap_geo",
    "toad_player_geo",
    "toads_cap_geo",
    "toads_metal_cap_geo",
    "toads_wing_cap_geo",
    "waluigi_geo",
    "waluigis_cap_geo",
    "waluigis_metal_cap_geo",
    "waluigis_wing_cap_geo",
    "waluigis_winged_metal_cap_geo",
    "wario_geo",
    "warios_cap_geo",
    "warios_metal_cap_geo",
    "warios_wing_cap_geo",
    "warios_winged_metal_cap_geo",
]
