GLOBAL_SCRIPT_SIGNATURES = {
    "script_func_global_1": (
        [
            ("LOAD_MODEL_FROM_GEO", "MODEL_BLUE_COIN_SWITCH", "blue_coin_switch_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_AMP", "amp_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_PURPLE_SWITCH", "purple_switch_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_CHECKERBOARD_PLATFORM", "checkerboard_platform_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_BREAKABLE_BOX", "breakable_box_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_BREAKABLE_BOX_SMALL", "breakable_box_small_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_EXCLAMATION_BOX_OUTLINE", "exclamation_box_outline_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_EXCLAMATION_BOX", "exclamation_box_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_GOOMBA", "goomba_geo"),
            (
                "LOAD_MODEL_FROM_DL",
                "MODEL_EXCLAMATION_POINT",
                "exclamation_box_outline_seg8_dl_08025F08",
                "LAYER_ALPHA",
            ),
            ("LOAD_MODEL_FROM_GEO", "MODEL_KOOPA_SHELL", "koopa_shell_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_METAL_BOX", "metal_box_geo"),
            ("LOAD_MODEL_FROM_DL", "MODEL_METAL_BOX_DL", "metal_box_dl", "LAYER_OPAQUE"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_BLACK_BOBOMB", "black_bobomb_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_BOBOMB_BUDDY", "bobomb_buddy_geo"),
            (
                "LOAD_MODEL_FROM_DL",
                "MODEL_DL_CANNON_LID",
                "cannon_lid_seg8_dl_080048E0",
                "LAYER_OPAQUE",
            ),
            ("LOAD_MODEL_FROM_GEO", "MODEL_BOWLING_BALL", "bowling_ball_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_CANNON_BARREL", "cannon_barrel_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_CANNON_BASE", "cannon_base_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_HEART", "heart_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_FLYGUY", "flyguy_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_CHUCKYA", "chuckya_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_TRAJECTORY_MARKER_BALL", "bowling_ball_track_geo"),
            ("RETURN",),
        ],
        "98878d05edf66c7323ef3392a6c4aa87c6d0c764bd78eb8a3315b6901d317f4a",
    ),
    "script_func_global_2": (
        [
            ("LOAD_MODEL_FROM_GEO", "MODEL_BULLET_BILL", "bullet_bill_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_YELLOW_SPHERE", "yellow_sphere_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_HOOT", "hoot_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_YOSHI_EGG", "yoshi_egg_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_THWOMP", "thwomp_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_HEAVE_HO", "heave_ho_geo"),
            ("RETURN",),
        ],
        "aa1603c6b1b38e10a9bcd155fd3cf2aceb097f70a5af40199f96b88710e5b8d9",
    ),
    "script_func_global_3": (
        [
            ("LOAD_MODEL_FROM_GEO", "MODEL_BLARGG", "blargg_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_BULLY", "bully_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_BULLY_BOSS", "bully_boss_geo"),
            ("RETURN",),
        ],
        "392cbf0b92d0b8ffa4fd25a35ab6f6f1e0fd7340623d6c8333a0e91ead364c95",
    ),
    "script_func_global_4": (
        [
            ("LOAD_MODEL_FROM_GEO", "MODEL_WATER_BOMB", "water_bomb_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_WATER_BOMB_SHADOW", "water_bomb_shadow_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_KING_BOBOMB", "king_bobomb_geo"),
            ("RETURN",),
        ],
        "1be6ca29308e8c70fff89397dd301fb3747ce2b0a3c01b1fab2aa185cd165897",
    ),
    "script_func_global_5": (
        [
            ("LOAD_MODEL_FROM_GEO", "MODEL_MANTA_RAY", "manta_seg5_geo_05008D14"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_UNAGI", "unagi_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_SUSHI", "sushi_geo"),
            (
                "LOAD_MODEL_FROM_DL",
                "MODEL_DL_WHIRLPOOL",
                "whirlpool_seg5_dl_05013CB8",
                "LAYER_TRANSPARENT",
            ),
            ("LOAD_MODEL_FROM_GEO", "MODEL_CLAM_SHELL", "clam_shell_geo"),
            ("RETURN",),
        ],
        "06ad9f186fb1c514aad4be112dfd26f781f62625c7f3d38c5e6a5356faa522ec",
    ),
    "script_func_global_6": (
        [
            ("LOAD_MODEL_FROM_GEO", "MODEL_POKEY_HEAD", "pokey_head_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_POKEY_BODY_PART", "pokey_body_part_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_TWEESTER", "tweester_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_KLEPTO", "klepto_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_EYEROK_LEFT_HAND", "eyerok_left_hand_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_EYEROK_RIGHT_HAND", "eyerok_right_hand_geo"),
            ("RETURN",),
        ],
        "acfe9d9f927f26381ee3af6a6e7ca82e6a5826e840875aa2f00ee896085f6588",
    ),
    "script_func_global_7": (
        [
            (
                "LOAD_MODEL_FROM_DL",
                "MODEL_DL_MONTY_MOLE_HOLE",
                "monty_mole_hole_seg5_dl_05000840",
                "LAYER_TRANSPARENT_DECAL",
            ),
            ("LOAD_MODEL_FROM_GEO", "MODEL_MONTY_MOLE", "monty_mole_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_UKIKI", "ukiki_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_FWOOSH", "fwoosh_geo"),
            ("RETURN",),
        ],
        "1514847a1e467c549888f4271f7142732d03e4ced684eb60acdcf03b80a92fd1",
    ),
    "script_func_global_8": (
        [
            ("LOAD_MODEL_FROM_GEO", "MODEL_SPINDRIFT", "spindrift_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_MR_BLIZZARD_HIDDEN", "mr_blizzard_hidden_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_MR_BLIZZARD", "mr_blizzard_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_PENGUIN", "penguin_geo"),
            ("RETURN",),
        ],
        "e6d8e6c3c937694ca7e9230236c9d8c2bc1c1110835025b3c0b6233aaaef4d96",
    ),
    "script_func_global_9": (
        [
            (
                "LOAD_MODEL_FROM_DL",
                "MODEL_CAP_SWITCH_EXCLAMATION",
                "cap_switch_exclamation_seg5_dl_05002E00",
                "LAYER_ALPHA",
            ),
            ("LOAD_MODEL_FROM_GEO", "MODEL_CAP_SWITCH", "cap_switch_geo"),
            (
                "LOAD_MODEL_FROM_DL",
                "MODEL_CAP_SWITCH_BASE",
                "cap_switch_base_seg5_dl_05003120",
                "LAYER_OPAQUE",
            ),
            ("RETURN",),
        ],
        "76b91873f2712b812c803d673fa8137329dba6fe2ba87b7ecf2adf944954802f",
    ),
    "script_func_global_10": (
        [
            ("LOAD_MODEL_FROM_GEO", "MODEL_BOO", "boo_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_BETA_BOO_KEY", "small_key_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_HAUNTED_CHAIR", "haunted_chair_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_MAD_PIANO", "mad_piano_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_BOOKEND_PART", "bookend_part_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_BOOKEND", "bookend_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_HAUNTED_CAGE", "haunted_cage_geo"),
            ("RETURN",),
        ],
        "2f0bfcaf854b6965c102bc029f695ec2aa187f6f746f5ff08ab5566d925ef22b",
    ),
    "script_func_global_11": (
        [
            ("LOAD_MODEL_FROM_GEO", "MODEL_BIRDS", "birds_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_PEACH", "peach_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_YOSHI", "yoshi_geo"),
            ("RETURN",),
        ],
        "2042a5ba21229999b1124f3a60dcdf0f5efbdf55bb330caa2e501cce4c84f497",
    ),
    "script_func_global_12": (
        [
            ("LOAD_MODEL_FROM_GEO", "MODEL_ENEMY_LAKITU", "enemy_lakitu_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_SPINY_BALL", "spiny_ball_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_SPINY", "spiny_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_WIGGLER_HEAD", "wiggler_head_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_WIGGLER_BODY", "wiggler_body_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_BUBBA", "bubba_geo"),
            ("RETURN",),
        ],
        "ef5d1e18239b0c7667974b6e2117ac8fd354a0314713bc00bb866d534de52210",
    ),
    "script_func_global_13": (
        [
            ("LOAD_MODEL_FROM_GEO", "MODEL_BOWSER", "bowser_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_BOWSER_BOMB_CHILD_OBJ", "bowser_bomb_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_BOWSER_BOMB", "bowser_bomb_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_BOWSER_SMOKE", "bowser_impact_smoke_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_BOWSER_FLAMES", "bowser_flames_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_BOWSER_WAVE", "invisible_bowser_accessory_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_BOWSER2", "bowser2_geo"),
            ("RETURN",),
        ],
        "7562efa57cdf6e44f577a4e3624b058cf6b3a3e82e884ccde1f4a00b6d4f5afa",
    ),
    "script_func_global_14": (
        [
            ("LOAD_MODEL_FROM_GEO", "MODEL_BUB", "bub_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_TREASURE_CHEST_BASE", "treasure_chest_base_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_TREASURE_CHEST_LID", "treasure_chest_lid_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_CYAN_FISH", "cyan_fish_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_WATER_RING", "water_ring_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_WATER_MINE", "water_mine_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_SEAWEED", "seaweed_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_SKEETER", "skeeter_geo"),
            ("RETURN",),
        ],
        "225b2e1002025f5b919520a0b20c5d2a802bc83f7197451a812af0bec75e06ff",
    ),
    "script_func_global_15": (
        [
            ("LOAD_MODEL_FROM_GEO", "MODEL_PIRANHA_PLANT", "piranha_plant_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_WHOMP", "whomp_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_KOOPA_WITH_SHELL", "koopa_with_shell_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_KOOPA_WITHOUT_SHELL", "koopa_without_shell_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_METALLIC_BALL", "metallic_ball_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_CHAIN_CHOMP", "chain_chomp_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_KOOPA_FLAG", "koopa_flag_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_WOODEN_POST", "wooden_post_geo"),
            ("RETURN",),
        ],
        "08737dec801c7a762f32d2c79e1b620fab0fc8f957b0fe0dda3410873a8356ce",
    ),
    "script_func_global_16": (
        [
            ("LOAD_MODEL_FROM_GEO", "MODEL_MIPS", "mips_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_BOO_CASTLE", "boo_castle_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_LAKITU", "lakitu_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_TOAD", "toad_geo"),
            ("RETURN",),
        ],
        "ad11ba712e3bf2974b97fecc4e2cc4d6af990e11d6ed0ab6ca915cbf5e453927",
    ),
    "script_func_global_17": (
        [
            ("LOAD_MODEL_FROM_GEO", "MODEL_CHILL_BULLY", "chilly_chief_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_BIG_CHILL_BULLY", "chilly_chief_big_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_MONEYBAG", "moneybag_geo"),
            ("RETURN",),
        ],
        "f1b456273a5bec5abe9bdf525d86a2517091eb0f41ff49d12e798b1a516a356f",
    ),
    "script_func_global_18": (
        [
            ("LOAD_MODEL_FROM_GEO", "MODEL_SWOOP", "swoop_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_SCUTTLEBUG", "scuttlebug_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_MR_I_IRIS", "mr_i_iris_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_MR_I", "mr_i_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_DORRIE", "dorrie_geo"),
            ("LOAD_MODEL_FROM_GEO", "MODEL_SNUFIT", "snufit_geo"),
            ("RETURN",),
        ],
        "f4fb298f74d2a60bd9f7557e2dd5b37eb2e16cb9d4877769dd1c895d1461c7c0",
    ),
}
